Repository carta/.github, pull requests merged in 2022-07, with the labels that each got.

#62 CW-303 add mypy_not_enrolled_linter
  .github/workflows/linters.yml
Labels: cc-config changes

#41 [CWS-1134] Add Flake8 to reusable workflow
  .github/actions/prepare_fixit_venv.yml
  .github/workflows/linters.yml
  configs/.flake8
  configs/mypy.ini
  requirements.txt
Labels: cc-product-development

#64 Revert "[CWS-1134] Add Flake8 to reusable workflow"
  .github/actions/prepare_fixit_venv.yml
  .github/workflows/linters.yml
  configs/.flake8
  configs/mypy.ini
  requirements.txt
Labels: cc-config changes

#66 Adding YAML validator
  .github/workflows/validator.yml
  .yamllint
Labels: cc-product-development

#65 [CWS-1134] Configuring Flake8 as a reusable workflow
  .github/actions/prepare_fixit_venv.yml
  .github/workflows/linters.yml
  configs/.flake8
  configs/mypy.ini
  requirements.txt
Labels: cc-product-development

#67 Fix requirements.txt raw URL
  .github/actions/prepare_fixit_venv.yml
  .yamllint
Labels: cc-bug

#69 CW-338 support poetry
  .github/workflows/linters.yml
Labels: cc-config changes

#68 Fix pep8 not found for flake8 run in carta-web
  .github/workflows/linters.yml
Labels: cc-bug

#70 CW-338 update cache key hash
  .github/actions/prepare_fixit_venv.yml
  .github/workflows/linters.yml
  fixit-requirements.txt
Labels: cc-config changes

#71 CW-338 update cache key
  .github/workflows/linters.yml
Labels: cc-config changes

#72 CW-338 download fixit-requirements.txt in the beginning
  .github/actions/prepare_fixit_venv.yml
  .github/workflows/linters.yml
Labels: cc-config changes

#74 Add a default mypy installation at venv
  .github/workflows/linters.yml
Labels: cc-bug
