Repository carta/.github, pull requests merged in 2022-05, with the labels that each got.

#37 CWS-1107 remove unused PR_REPO env var
  .github/workflows/linters.yml
Labels: cc-config changes

#38 [CWS-1107] Run checkrun on Mypy for success state
  .github/workflows/linters.yml
Labels: cc-product-development

#39 [CWS-1016] Allow reusable workflow to receive extra mypy configs
  .github/workflows/linters.yml
  configs/mypy.ini
Labels: cc-config changes

#42 [CWS-1132] Create log path for Mypy Linter
  .github/workflows/linters.yml
Labels: cc-bug

#43 CW-57 remove unsed type_annotation.yml
  .github/workflows/type_annotation.yml
Labels: cc-config changes

#44 CW-57 remove unused PR_NUMBER env
  .github/workflows/linters.yml
Labels: cc-config changes

#45 CW-57 add CODEOWNERS
  .github/CODEOWNERS
Labels: cc-config changes

#46 CW-57 enable run_fixit_linters on other GitHub events
  .github/workflows/linters.yml
Labels: cc-config changes

#47 CWS-1162 Fix LibCST parsing error on Python 3.10
  .github/workflows/linters.yml
Labels: cc-config changes

#48 CWS-1163 Cache fixit venv to speed up workflow
  .github/workflows/linters.yml
Labels: cc-config changes

#49 CWS-1163 consolidate Mypy venv to speed up workflow
  .github/workflows/linters.yml
Labels: cc-config changes

#50 CWS-1161 use composite actions
  .github/actions/checkout.yml
  .github/actions/prepare_fixit_venv.yml
  .github/workflows/linters.yml
Labels: cc-config changes

#51 CWS-1161 skip fetching cache pip artifacts when found venv
  .github/workflows/linters.yml
Labels: cc-config changes

#52 CW-269 Rerun only pull_request linter when PR is edited
  .github/workflows/linters.yml
Labels: cc-config changes

#53 CW-264 Move rebase to reusable workflow
  .github/workflows/labels.yml
Labels: cc-config changes
